# fly.toml app configuration file generated for live-fridge on 2024-10-29T23:05:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'live-fridge'
primary_region = 'ord'
kill_signal = 'SIGTERM'

[build]

[deploy]

[env]
  PHX_HOST = 'live-fridge.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
